### ISSUE TITLE
Example Fails with EnglishV3Slim PaddleOCR Model

### ISSUE THREAD

**Issue by theonewolf** [sdcb/mini-openvino-paddleocr#3]
@sdcb I tried with this code:

```C#
FullOcrModel model = await OnlineFullModels.EnglishV3Slim.DownloadAsync();
```

and it always raises this exception:

```
Sdcb.OpenVINO.OpenVINOException
  HResult=0x80131500
  Message=general error(-1) in file "C:\Users\ZhouJie\source\repos\OpenVINO.NET\src\Sdcb.OpenVINO\OVCore.cs" member "ReadModel" at line 210 when calling "ov_core_read_model_unicode((ov_core*)Handle, modelPathPtr, binPathPtr, &model)"
  Source=Sdcb.OpenVINO
  StackTrace:
   at Sdcb.OpenVINO.OpenVINOException.ThrowIfFailed(ov_status_e e, String message, String callerMemberName, String callerExpression, String callerFilePath, Nullable`1 callerLineNumber) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\src\Sdcb.OpenVINO\OpenVINOException.cs:line 51
   at Sdcb.OpenVINO.OVCore.ReadModel(String modelPath, String binPath) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\src\Sdcb.OpenVINO\OVCore.cs:line 210
   at Sdcb.OpenVINO.PaddleOCR.PaddleOVCoreExtensions.ReadDirectoryPaddleModel(OVCore core, String directoryPath, String modelFileName) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\projects\PaddleOCR\Sdcb.OpenVINO.PaddleOCR\PaddleOVCoreExtensions.cs:line 22
   at Sdcb.OpenVINO.PaddleOCR.Models.Details.FileDetectionModel.CreateOVModel(OVCore core) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\projects\PaddleOCR\Sdcb.OpenVINO.PaddleOCR\Models\Details\FileDetectionModel.cs:line 30
   at Sdcb.OpenVINO.BaseModel.CreateCompiledModel(DeviceOptions options, Action`1 afterReadModel, Action`2 prePostProcessing, Action`1 afterBuildModel, Action`1 afterCompiledModel) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\src\Sdcb.OpenVINO\BaseModel.cs:line 46
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrDetector..ctor(DetectionModel model, DeviceOptions options, Nullable`1 staticShapeSize) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\projects\PaddleOCR\Sdcb.OpenVINO.PaddleOCR\PaddleOcrDetector.cs:line 79
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrAll..ctor(FullOcrModel model, PaddleOcrOptions options) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\projects\PaddleOCR\Sdcb.OpenVINO.PaddleOCR\PaddleOcrAll.cs:line 54
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrAll..ctor(FullOcrModel model, DeviceOptions device) in C:\Users\ZhouJie\source\repos\OpenVINO.NET\projects\PaddleOCR\Sdcb.OpenVINO.PaddleOCR\PaddleOcrAll.cs:line 45
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\WolfgangRichter\Development\Experiments\Experiments\mini-openvino-paddleocr\mini-openvino-paddleocr\Program.cs:line 13
   at Program.<Main>(String[] args)
```

I did notice in my cache it properly downloaded the V3 slim model.

**Comment by sdcb** [comment]
It seems have some problem with EnglishV3Slim, can you try with EnglishV3 or EnglishV4 instead?

**Comment by theonewolf** [comment]
@sdcb I also saw it have a problem with ChineseV3Slim.  Both Slim models.

I got it working with EnglishV3 and also EnglishV4.

But they use more RAM than I am allowed.

I was really hoping to test with slim models and see if they use much less RAM :-)

**Comment by sdcb** [comment]
I believe it's an issue that upstream [openvino](https://github.com/openvinotoolkit/openvino) does not supports slim models.

**Comment by theonewolf** [comment]
Should we make a C++ program to see the error in more detail?  I am trying to understand the exact error, to know if it's fixable or not.

**Comment by theonewolf** [comment]
@sdcb do any of your other projects support Paddle slim models?  I am trying to cut down memory usage.

@sdcb I think OpenVino doesn't support some operators used by the slim Paddle models.

Here's what I got from Python:

```python
>>> import openvino as ov
>>> core = ov.Core()
>>> device = 'AUTO'
>>> det_model_file_path = r"C:\Users\WolfgangRichter\AppData\Roaming\paddleocr-models\en_PP-OCRv3_det_slim\inference.pdmodel"
>>> det_model = core.read_model(model=det_model_file_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\WolfgangRichter\Development\venvs\vinopaddletest\lib\site-packages\openvino\runtime\ie_api.py", line 507, in read_model
    return Model(super().read_model(model))
RuntimeError: Exception from src\inference\src\core.cpp:99:
Check 'creator_it != CREATORS_MAP.end()' failed at src\frontends\paddle\src\frontend.cpp:55:
FrontEnd API failed with OpConversionFailure:
No creator found for fake_quantize_dequantize_moving_average_abs_max node
```

**Comment by sdcb** [comment]
Oh, Wow, thanks for you to check this deeply detailed, can you try create a ticket in [openvino](https://github.com/openvinotoolkit/openvino)? I believe paddlepaddle have some cooperation with OpenVINO project, OpenVINO.NET is just a C API wrapper of OpenVINO.

**Comment by sdcb** [comment]
I wants to highlight that in coming 2023.2 version, OpenVINO supports provide detailed error information in C API according to my this issue: 
* https://github.com/openvinotoolkit/openvino/issues/20536

I already added support in coming release.

**Comment by theonewolf** [comment]
@sdcb your work is really nice, and I care a lot about getting low RAM OCR :-p so I am investigating all angles!

**Comment by sdcb** [comment]
Can you try lower the inference thread count, that should able to getting lower RAM, like this:
```csharp
using PaddleOcrAll all = new(model, new PaddleOcrOptions(new DeviceOptions("CPU")
{
	InferenceNumThreads = 1, // This should able to lower the RAM usage but also slower
	//NumStreams = 1, 
})
{
})
{
	Enable180Classification = true,
	AllowRotateDetection = true,
};

```

**Comment by theonewolf** [comment]
@sdcb not a huge difference for me, still 500-600 MB used, and I'd like it to be 250-300 MB of RAM.

Thanks though!  I'm very curious how much RAM the slim models would take, and how to get them running in C#.

**Comment by sdcb** [comment]
Hi @theonewolf , I upgraded into 2023.2, now OpenVINO.NET supports reflects errors from OpenVINO C API, in this case, it shows following error:

```
general error(-1) Exception from src\inference\src\core.cpp:94:
Check 'creator_it != CREATORS_MAP.end()' failed at src\frontends\paddle\src\frontend.cpp:55:
FrontEnd API failed with OpConversionFailure:
No creator found for fake_quantize_dequantize_moving_average_abs_max node.

 in file "C:\Users\sdfly\source\repos\OpenVINO.NET\src\Sdcb.OpenVINO\OVCore.cs" member "ReadModel" at line 213 when calling "ov_core_read_model_unicode((ov_core*)Handle, modelPathPtr, binPathPtr, &model)
```

Stack trace:
```
   at Sdcb.OpenVINO.OpenVINOException.ThrowIfFailed(ov_status_e e, String message, String callerMemberName, String callerExpression, String callerFilePath, Nullable`1 callerLineNumber)
   at Sdcb.OpenVINO.OVCore.ReadModel(String modelPath, String binPath)
   at Sdcb.OpenVINO.PaddleOCR.PaddleOVCoreExtensions.ReadDirectoryPaddleModel(OVCore core, String directoryPath, String modelFileName)
   at Sdcb.OpenVINO.PaddleOCR.Models.Details.FileDetectionModel.CreateOVModel(OVCore core)
   at Sdcb.OpenVINO.BaseModel.CreateCompiledModel(DeviceOptions options, Action`1 afterReadModel, Action`2 prePostProcessing, Action`1 afterBuildModel, Action`1 afterCompiledModel)
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrDetector..ctor(DetectionModel model, DeviceOptions options, Nullable`1 staticShapeSize)
   at Sdcb.OpenVINO.PaddleOCR.PaddleOcrAll..ctor(FullOcrModel model, PaddleOcrOptions options)
   at UserQuery.Main(), line 15
```

Now C# API also let you know it's caused by `fake_quantize_dequantize_moving_average_abs_max` now.
